{{- if .Values.server.ingress.enabled }}
{{- $serviceName := include "openbao.fullname" . }}
{{- $servicePort := .Values.server.service.port }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "openbao.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbao.labels" . | nindent 4 }}
  {{- with .Values.server.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.server.ingress.ingressClassName }}
  ingressClassName: {{ .Values.server.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.server.ingress.tls }}
  tls:
    {{- range .Values.server.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      {{- if .secretName }}
      secretName: {{ .secretName }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.server.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
          {{- end }}
    {{- end }}
{{- end }}
