{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openbao.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbao.labels" . | nindent 4 }}
  {{- $annotations := merge (dict) .Values.serviceAccount.annotations }}
  {{- if and .Values.seal.awskms.enabled .Values.seal.awskms.irsaRoleArn }}
  {{- $_ := set $annotations "eks.amazonaws.com/role-arn" .Values.seal.awskms.irsaRoleArn }}
  {{- end }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
