{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openbao.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbao.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8200
      targetPort: 8200
      protocol: TCP
  selector:
    {{- include "openbao.selectorLabels" . | nindent 4 }}
{{- end }}
