name: Release Helm Chart

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  HELM_VERSION: v3.17.2

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: git clone --depth 1 "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@${GITHUB_SERVER_URL#https://}/${{ github.repository }}.git" .

      - run: curl -sL https://get.helm.sh/helm-$HELM_VERSION-linux-amd64.tar.gz | tar xz --strip-components=1 -C /usr/local/bin linux-amd64/helm

      - name: Package chart
        run: |
          mkdir -p .dist
          helm package helm/openbao/ --destination .dist/
          helm repo index .dist/ --url "https://${{ github.repository }}/releases/download/${{ github.ref_name }}"

      - name: Create Release
        run: |
          gh release create "${{ github.ref_name }}" \
            .dist/*.tgz .dist/index.yaml \
            --title "${{ github.ref_name }}" \
            --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
